apiVersion: v1
kind: Secret

metadata:
  name: taskmanager-secret

type: Opaque

stringData:
  MONGO_INITDB_ROOT_USERNAME: YOUR_USERNAME
  MONGO_INITDB_ROOT_PASSWORD: YOUR_PASSWORD
  MONGO_URI: mongodb://YOUR_USERNAME:YOUR_PASSWORD@mongodb-service:27017/taskmanager?authSource=admin
